version: '3'

services:
  eureka:
    build: 
      context: eureka
    image: conchobar/eureka:latest
    ports: 
      - "8761:8761"
    expose:
      - "8761"

  travel_agent:
    build: 
      context: ./travel_agent
    image: conchobar/travel_agent:latest
    depends_on:
      - eureka
      - flights
      - hotels
      - activities
      - attractions
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    links:
      - eureka
    ports:
      - "8081:8081"
    expose:
      - "8081"

  flights:
    build: 
      context: ./flights
    image: conchobar/flights:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - eureka
    ports:
      - "8082:8082"
    expose:
      - "8082"

  hotels:
    build: 
      context: ./hotels
    image: conchobar/hotels:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - eureka
    ports:
      - "8089:8089"
    expose:
      - "8089"

  activities:
    build: 
      context: ./activities
    image: conchobar/activities:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - eureka
    ports:
      - "8083:8083"
    expose:
      - "8083"

  attractions:
    build: 
      context: ./attractions
    image: conchobar/attractions:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - eureka
    ports:
      - "8086:8086"
    expose:
      - "8086"
   




  