apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: attractions
  name: attractions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: attractions
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app: attractions
    spec:
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: _JAVA_OPTIONS
          value: -Deureka.client.serviceUrl.defaultZone=http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/ -Deureka.instance.preferIpAddress=true
        - name: EUREKA_CLIENT_REGISTERWITHEUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCHREGISTRY
          value: "true"
        image: conchobar/attractions:latest
        imagePullPolicy: ""
        name: attractions
        ports:
        - containerPort: 8086
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
