apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: attractions
  name: attractions
spec:
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
  selector:
    iapp: attractions
status:
  loadBalancer: {}
