apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: flights
  name: flights-service
spec:
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app: flights
status:
  loadBalancer: {}
